#!/usr/bin/env bash
echo "=== DEMO RECORDING SETUP ==="
echo "To record your demo, choose one method:"
echo ""
echo "METHOD 1 - OBS Studio (Recommended):"
echo "1. Install: sudo apt install obs-studio"
echo "2. Launch: obs-studio"
echo "3. Set up screen capture and microphone"
echo "4. Record while following demo_script.txt"
echo ""
echo "METHOD 2 - FFmpeg (Terminal only):"
echo "ffmpeg -video_size 1366x768 -framerate 15 -f x11grab -i :0.0 \\"
echo "       -f pulse -i default -c:v libx264 -preset ultrafast \\"
echo "       capstone-demo-Kosana.mp4"
echo ""
echo "Demo script: demo_script.txt"
echo "Estimated time: 3-5 minutes"
